name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_USERNAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_USERNAME }}.azurecr.io/nodejsmicroservice:${{ github.sha }} ./nodejs-microservice

    - name: Push Docker image to ACR
      run: docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/nodejsmicroservice:${{ github.sha }}
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure Service Principal

    - name: Update ACI with new image
      run: |
        az container create --resource-group CapstoneResourceGroup --name capstoneacisameer --image capstonesameeracr.azurecr.io/nodejsmicroservice:${{ github.sha }} --registry-login-server capstonesameeracr.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}
