name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ***.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ***.azurecr.io/nodejsmicroservice:${{ github.sha }} ./nodejs-microservice

    - name: Push Docker image to ACR
      run: docker push ***.azurecr.io/nodejsmicroservice:${{ github.sha }}
